### ISSUE TITLE
Mod worked for a bit, stopped working. Won't Connect

### ISSUE THREAD

**Issue by TheRealTommyQ** [Epicguru/RimVibesMod#3]
![RimVibe Issue Report 1](https://user-images.githubusercontent.com/65424378/82096718-b43bec00-96be-11ea-9ced-36db43dfd6b2.PNG)
I get the typical Disconnected prompt. I've tried reinstalling the mod, Rimworld, disconnecting my Spotify account, and restarting Spotify and my computer. 

![RimVibe Issue Report 2](https://user-images.githubusercontent.com/65424378/82096830-f107e300-96be-11ea-9514-6e931b4e6604.PNG)
When pulling up the debug log I get this message.

**Comment by Epicguru** [comment]
@TheRealTommyQ Thanks for report, this has now been fixed with latest update.
I'll close this issue if no more errors are reported.
